/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package layout;

import java.awt.CardLayout;

/**
 *
 * @author mochd
 */
public class Coba extends javax.swing.JFrame {

    /**
     * Creates new form Coba
     */
    public Coba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btn_indo = new javax.swing.JButton();
        btn_jpn = new javax.swing.JButton();
        btn_russia = new javax.swing.JButton();
        btn_thai = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_indo.setText("jButton1");
        btn_indo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_indoActionPerformed(evt);
            }
        });
        buttonPanel.add(btn_indo);

        btn_jpn.setText("jButton2");
        btn_jpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jpnActionPerformed(evt);
            }
        });
        buttonPanel.add(btn_jpn);

        btn_russia.setText("jButton3");
        btn_russia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_russiaActionPerformed(evt);
            }
        });
        buttonPanel.add(btn_russia);

        btn_thai.setText("jButton4");
        btn_thai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thaiActionPerformed(evt);
            }
        });
        buttonPanel.add(btn_thai);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/indonesia.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        imagePanel.add(jLabel1, "0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/jepang.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        imagePanel.add(jLabel2, "1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/russia.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        imagePanel.add(jLabel3, "2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/thailand.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        imagePanel.add(jLabel4, "3");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_indoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_indoActionPerformed
        CardLayout CardLayout = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_btn_indoActionPerformed

    private void btn_jpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jpnActionPerformed
       CardLayout CardLayout = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel,"1");
    }//GEN-LAST:event_btn_jpnActionPerformed

    private void btn_russiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_russiaActionPerformed
        CardLayout CardLayout = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel,"2");
    }//GEN-LAST:event_btn_russiaActionPerformed

    private void btn_thaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thaiActionPerformed
        CardLayout CardLayout = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel,"3");
    }//GEN-LAST:event_btn_thaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_indo;
    private javax.swing.JButton btn_jpn;
    private javax.swing.JButton btn_russia;
    private javax.swing.JButton btn_thai;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
